Add serial support
DoumanAsh/stm32l4x6_hal pull request #5
Opened 2018-04-27 05:43 UTC by thenewwazoo

Another fairly early PR; this builds up the `composable-clocks` branch.

2018-04-27 05:49 UTC, thenewwazoo commented
[This commit](https://github.com/DoumanAsh/stm32l4x6_hal/pull/5/commits/cb8e0b06a90fea4f4027c985fbdb9ebe4df58983) is basically the thing to look at (the rest is relative noise from `composable-clocks`)

2018-04-27 17:26 UTC, DoumanAsh requested changes
Thanks for your PR!

2018-04-27 17:26 UTC, DoumanAsh commented on src/gpio/mod.rs
> +                //ahb.rstr2().modify(|_, w| w.$gpiorst().set_bit());
It is not needed?
Why you left it commented out?

2018-04-27 17:26 UTC, DoumanAsh commented on src/gpio/mod.rs
> +            pub fn set_pin_speed(&self, spd: PinSpeed, ospeedr: &mut OSPEEDR<$GPIOX>) {
Can you please add documentation for it?

2018-04-27 17:26 UTC, DoumanAsh commented on src/gpio/mod.rs
> +                    // AFRx pin fields are 4 bits wide, and each 8-pin bank has its own reg (L or
Oh thx for fixing it.
Can you please also add reference to manual? I like to keep them around in case I'd need to review this code in future

2018-04-27 17:26 UTC, DoumanAsh commented on src/rcc.rs
> +            let vco_if = src.freq() / m as u32;
Could you please add comments on what are these vco_*?

2018-04-27 17:26 UTC, DoumanAsh commented on src/rcc.rs
> +    pub enum USARTClkSource {
Please describe pub items here and below with documentation (including their variants)

2018-04-27 17:26 UTC, DoumanAsh commented on src/rcc.rs
> +        PCLK(PeripheralClock), /// U(S)ART-specific peripheral clock (PCLK1, PCLK2)
Please keep style of enum variants docs like:
```rust
///doc
Variant
```

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +
Remove empty line

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +                        panic!("impossible BRR");
By impossible do you mean it is theoretically impossible for user to configure clock in a way that such bad rate would appear?
If it is then ok, but if it is user mis-configuration then I'd suggest to change panic message to something like;
`Bad clock frequency leads to baud rate below 16`

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +                where
It may sound strange but I prefer short traits to be besides function itself rather than `Where` section.
i.e. I'd prefer `pub nf $uartX<TX: TxPin<$USARTX>, RX: RxPin<$USARTX>>()`

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +    Rxne,
Can we have better names for Event's variants? I understand it is close to HW this way, but something like `Event::Receive` would be better than `Event::Rxne` :)

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +                            ptr::write_volatile(&(*$USARTX::ptr()).tdr as *const _ as *mut _, byte)
Can you please add note that it clears ISR's TC register for future reference?

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +                            ptr::read_volatile(&(*$USARTX::ptr()).rdr as *const _ as *const _)
Please add note for future reference that read of RDR clears ISR's RXNE

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +pub struct Rx<USART> {
Consider using unit struct instead of having unused member?
i.e. `pub struct Rx<USART>(PhantomData<USART>)`

The same for Tx

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +                    usart.cr3.modify(|_,w| w.rtse().clear_bit().ctse().clear_bit()); // no hardware flow control
Should this aspect be custom option maybe?
Also, isn't RTSE & CTSE is disabled by default?

Note that I'm not familiar with USART so let me know if it is bad idea to enable it

2018-04-27 17:26 UTC, DoumanAsh commented on src/serial/mod.rs
> +                    while apb.$enr().read().$usartXen().bit_is_clear() {} // __HAL_RCC_USART2_CLK_ENABLE <- HAL_UART_MspInit <- HAL_UART_Init
General about in-code commnets.
Could you please replace references to, I suspect, C's HAL with meaningful comments about meaning of instruction?

2018-09-08 04:57 UTC, thenewwazoo commented
I'm going to close this and resubmit once I'm working with this chip again (should only be a few days/week).

2018-09-08 04:57 UTC, closed without merging